### ISSUE TITLE
Error when checking input: expected conv2d_1_input to have shape (None, 61, 61, 2)

### ISSUE THREAD

**Issue by BTurkowyd** [CovertLab/DeepCell#13]
Good evening,

In last days I have found your article about DeepCell and it is very interesting and useful, thus I wish to apply it in future in my research. Currently I am trying to get into it with data provided by you, however, I have a problem with training the cov-net. I constantly get an error:

> Error when checking input: expected conv2d_22_input to have shape (None, 61, 61, 2) but got array with shape (58859, 2, 61, 61)

As far as I understood (probably), script expects to have a TensorFlow format (NWHC, N-samples, width, height, class), but gets Theano format (NCWH). Is this a correct conclusion? Because I am using your npz files, I didn't modify them at all, python files as well, I am clueless what to do. 

I used **"bn_feature_net_61x61"** model on **3T3_all_61x61.npz** file (**Python 2.7, Ubuntu 16.04.3**). Previously I was trying _E. coli_ data as I am working with these organisms, but with 3T3 I progressed most.

I am hoping for your answer and advise.

Kindly regards,
Bartosz

**Comment by vanvalen** [comment]
Check the keras settings, as it should be expecting and receiving the channels first format. I'm working on a new version written in the latest keras with a tensorflow back end.

**Comment by BTurkowyd** [comment]
I have tried both, Theano and TensorFlow, already, error stays the same. I will dig more.

Here is the error message, looks exactly the same for Theano and TensorFlow backend:

> Traceback (most recent call last):

> 
>   File "<ipython-input-2-f2935d48cc31>", line 34, in <module>
>     rotate = True, flip = True, shear = False)
> 
>   File "cnn_functions.py", line 1392, in train_model_sample
>     LearningRateScheduler(lr_sched)])
> 
>   File "/home/bartosz/anaconda2/lib/python2.7/site-packages/keras/legacy/interfaces.py", line 87, in wrapper
>     return func(*args, **kwargs)
> 
>   File "/home/bartosz/anaconda2/lib/python2.7/site-packages/keras/models.py", line 1121, in fit_generator
>     initial_epoch=initial_epoch)
> 
>   File "/home/bartosz/anaconda2/lib/python2.7/site-packages/keras/legacy/interfaces.py", line 87, in wrapper
>     return func(*args, **kwargs)
> 
>   File "/home/bartosz/anaconda2/lib/python2.7/site-packages/keras/engine/training.py", line 1978, in fit_generator
>     val_x, val_y, val_sample_weight)
> 
>   File "/home/bartosz/anaconda2/lib/python2.7/site-packages/keras/engine/training.py", line 1378, in _standardize_user_data
>     exception_prefix='input')
> 
>   File "/home/bartosz/anaconda2/lib/python2.7/site-packages/keras/engine/training.py", line 144, in _standardize_input_data
>     str(array.shape))
> 
> ValueError: Error when checking input: expected conv2d_1_input to have shape (None, 61, 61, 2) but got array with shape (19619, 2, 61, 61)

**Comment by BTurkowyd** [comment]
Ok, problem is solved. I figured out that my keras was using TensorFlow backend and it should use Theano. Also, I reinstalled keras to older version. Both, E. coli and 3T3 cells are processed normally!

Thanks again for this fascinating approach in cell segmentation!

Best,
Bartosz
