### ISSUE TITLE
error in file IO of a training data npz exactly where it is but can't find it.

### ISSUE THREAD

**Issue by hftsai** [CovertLab/DeepCell#8]
Hi,
deepcell looks really really awesome and seems to be doing a great job segmenting touching cells. So I am really interested in doing cell tracking taken on phase contrast microscope.
I've been trying to do it in Unet and modified Segnet but the results haven't been very promising.

But when i'm just following your tutorial on training convnets notebook.
(I run the docker version. because trying to build has it's own problem from newer version of keras)
It shows a error trying to find the training data npz.
I have the file exactly where it is but it keep showing it cannot find the file.
```

IOErrorTraceback (most recent call last)
<ipython-input-12-bbf0fd3fe821> in <module>()
      8                 direc_data = direc_data,
      9                 lr_sched = lr_sched,
---> 10 		rotate = True, flip = True, shear = False)
     11 
     12         del model

/root/DeepCell/keras_version/cnn_functions.py in train_model_sample(model, dataset, optimizer, expt, it, batch_size, n_epoch, direc_save, direc_data, lr_sched, rotate, flip, shear, class_weight)
   1326         file_name_save_loss = os.path.join(direc_save, todays_date + "_" + dataset + "_" + expt + "_" + str(it) + ".npz")
   1327 
-> 1328         train_dict, (X_test, Y_test) = get_data_sample(training_data_file_name)
   1329 
   1330         # the data, shuffled and split between train and test sets

/root/DeepCell/keras_version/cnn_functions.py in get_data_sample(file_name)
    360 
    361 def get_data_sample(file_name):
--> 362         training_data = np.load(file_name)
    363         channels = training_data["channels"]
    364         batch = training_data["batch"]

/root/.pyenv/versions/2.7.4/envs/DeepCell/lib/python2.7/site-packages/numpy/lib/npyio.pyc in load(file, mmap_mode, allow_pickle, fix_imports, encoding)
    360     own_fid = False
    361     if isinstance(file, basestring):
--> 362         fid = open(file, "rb")
    363         own_fid = True
    364     else:

IOError: [Errno 2] No such file or directory: '/home/davince/DeepCell2/training_data_npz/3T3/3T3_all_61x61.npz'

```
But is there something i misunderstood?

I also have interest of doing cell tracking.
But there is another software lineage mapper from NIST seems could work as long there is a good segmentation mask (which is exactly what deepcell results looks so awesome to me)
Thanks

**Comment by vanvalen** [comment]
If I had to guess
'/home/davince/DeepCell2/training_data_npz/3T3/3T3_all_61x61.npz'
should be '/home/davince/DeepCell/training_data_npz/3T3/3T3_all_61x61.npz',
but I'm not sure since I don't know all of the changes you made to the
code.

Best,

Dave


David Van Valen MD, PhD
Postdoctoral Scholar, Covert Lab
Stanford University

**Comment by hftsai** [comment]
Sorry for the late reply.
Hi Dave.
First thank you for this super cool tool! hopefully i could get it to work as well as you.
you're awesome. 

I think i figured out some of it. Because I was following the jupyter notebook. And i'm very new to this. there is something might help others if they are as careless as me.
1. If you have also tensorflow installed. besure to configure keras to use Theano backend.
2. Make sure the data are under the same mother directory as the jupyter notebook and other files. access permission problems might give rise to IO error.

At least after i checked these, I could proceed on training.
I'll also try to start a new fork to modify codes that will later by deprecated by keras 2 API.
